
    import vaporfly from "$lib/images/vaporfly.png"


 const shoes = [
    {
        name: 'Nike ZoomX Vaporfly Next% 2',
        price: 250,
        bestUse: "Distance racing",
        surface: "Road",
        rating: "★★★★★",
        img: vaporfly,
        weight: 196,
        drop: 7.7,
        heelStackHeight: 38.6,
        forefootStackHeight: 30.9,
        arch: "Neutral",
        brand: "Nike",
        brandLogo: "https://static.nike.com/a/images/f_jpg,q_auto:eco/61b4738b-e1e1-4786-8f6c-26aa0008e80b/swoosh-logo-black.png",
        link: "https://www.runningwarehouse.com/Mens_Nike_Vaporfly/catpage-MVAPORFLY.html",
        brandLink: "https://www.nike.com/w?q=vaporfly&vst=vaporfly",
        review: "stuff",
        id: 'nike-zoomx-vaporfly-next-2',
    },
    {
        name: 'Nike ZoomX Drangonfly',
        price: 150,
        bestUse: "Distance racing",
        surface: "Track",
        rating: "★★★★★",
        img: "https://cdn.shopify.com/s/files/1/1804/7057/products/DJ5255-100-PHSRH000-2000_2000x2000.png?v=1671051158",
        weight: 196,
        drop: 7.7,
        heelStackHeight: 38.6,
        forefootStackHeight: 30.9,
        arch: "Neutral",
        brand: "Nike",
        brandLogo: "https://static.nike.com/a/images/f_jpg,q_auto:eco/61b4738b-e1e1-4786-8f6c-26aa0008e80b/swoosh-logo-black.png",
        link: "https://www.runningwarehouse.com/Mens_Nike_Vaporfly/catpage-MVAPORFLY.html",
        brandLink: "https://www.nike.com/w?q=vaporfly&vst=vaporfly",
        review: "stuff",
        id: 'nike-zoomx-dragonfly',
    },
     {
         name: 'On Cloudmonster',
         price: 169.99,
         bestUse: "Training",
         surface: "Road",
         rating: "★★★★",
         img: "https://images.ctfassets.net/hnk2vsx53n6l/2Az75p1g0Oh5Am8B1n1mJQ/96d8dc8578cc3ed817e865505c47e070/9e1bbeb325c15e3cc3a21ed721cb84e80965efb9.png?w=800&h=800&fm=png&f=center&fit=fill&q=80",
         weight: 264,
         drop: 6.8,
         heelStackHeight: 34.9,
         forefootStackHeight: 28.1,
         arch: "Neutral",
         foam: "Helion (hydorgen infused EVA?)",
         brand: "Nike",
         brandLogo: "https://www.therunnershub.net/wp-content/uploads/2017/01/11249876_1635506986735635_175419393_a-300x300.jpg",
         link: "https://www.runningwarehouse.com/search-mens.html?searchtext=cloudmonster&opt_perpage=20&opt_sort=relevance&opt_page=1",
         brandLink: "https://www.on-running.com/en-us/products/cloudmonster-61",
         review: "stuff",
         id: 'on-cloudmonster',
     },
     {
         name: 'Nike ZoomX Streakfly',
         price: 160,
         bestUse: "Distance racing",
         surface: "Road",
         rating: "★★★★",
         img: "https://static.nike.com/a/images/t_default/24d5a5ec-db76-4512-99a8-36231b9a9b41/streakfly-road-racing-shoes-V17qZm.png",
         weight: 196,
         drop: 7.7,
         heelStackHeight: 38.6,
         forefootStackHeight: 30.9,
         arch: "Neutral",
         brand: "Nike",
         brandLogo: "https://static.nike.com/a/images/f_jpg,q_auto:eco/61b4738b-e1e1-4786-8f6c-26aa0008e80b/swoosh-logo-black.png",
         link: "https://www.runningwarehouse.com/Mens_Nike_Vaporfly/catpage-MVAPORFLY.html",
         brandLink: "https://www.nike.com/w?q=vaporfly&vst=vaporfly",
         review: "stuff",
         id: 'nike-zoomx-streakfly',
     },
     {
         name: 'Nike Air Zoom Victory',
         price: 180,
         bestUse: "Distance racing",
         surface: "Track",
         rating: "★★★★★",
         img: "https://cdn.shopify.com/s/files/1/0596/8776/4165/products/CD4385-700-PHSRH000-2000_1024x1024.png?v=1666155142",
         weight: 196,
         drop: 7.7,
         heelStackHeight: 38.6,
         forefootStackHeight: 30.9,
         arch: "Neutral",
         brand: "Nike",
         brandLogo: "https://static.nike.com/a/images/f_jpg,q_auto:eco/61b4738b-e1e1-4786-8f6c-26aa0008e80b/swoosh-logo-black.png",
         link: "https://www.runningwarehouse.com/Mens_Nike_Vaporfly/catpage-MVAPORFLY.html",
         brandLink: "https://www.nike.com/w?q=vaporfly&vst=vaporfly",
         review: "stuff",
         id: 'nike-air-zoom-victory',
     }

]
 export {shoes}
